const data = [
    { id: 1, name: 'New York' },
    { id: 2, name: 'Los Angeles' },
    { id: 3, name: 'Chicago' },
    { id: 4, name: 'Houston' },
    { id: 5, name: 'Phoenix' },
    { id: 6, name: 'Philadelphia' },
    { id: 7, name: 'San Antonio' },
    { id: 8, name: 'San Diego' },
    { id: 9, name: 'Dallas' },
    { id: 10, name: 'San Jose' },
    { id: 11, name: 'John' },
    { id: 12, name: 'Alice' },
    { id: 13, name: 'Bob' },
    { id: 14, name: 'Charlie' },
    { id: 15, name: 'David' },
    { id: 16, name: 'Emily' },
    { id: 17, name: 'JavaScript' },
    { id: 18, name: 'Python' },
    { id: 19, name: 'Java' },
    { id: 20, name: 'C#' },
    { id: 21, name: 'Ruby' },
    { id: 22, name: 'PHP' },
    { id: 23, name: 'C++' },
    { id: 24, name: 'Go' },
    { id: 25, name: 'Swift' },
]

export {data };